import Head from "next/head";
import Header from "../components/Header";
import {getProviders, signIn} from 'next-auth/react'

export default function home({providers}) {
  console.log(providers);
  return (
    <div>
      <Head>
        <title>Disney | Login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}

export async function getServerSideProps(context) {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}