import Head from 'next/head'
import Header from '../components/Header'
import { signOut } from "next-auth/react"

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    <button onClick={() => signOut()}>Sign out</button>
   
    </div>
  )
}
